### ISSUE TITLE
After klicking "Upload" I would like to see a progress bar

### ISSUE THREAD

**Issue by tibfox** [techcoderx/ipfsVideoUploader#1]
As user of the service I would like to see the status of uploading in any kind after I pressed the Button "Upload". This would give the end user a response of the current action and let him also know how far the upload is currently.
Instead of that would probably also be enough to show a turning wheel for the sign that something is still working.

**Comment by techcoderx** [comment]
Added in [this commit](https://github.com/techcoderx/ipfsVideoUploader/commit/38d226fcd9f37b2e1f4364ca3b8bb7daa59dd8ed)
