### ISSUE TITLE
Possibility to add steemit post

### ISSUE THREAD

**Issue by tibfox** [techcoderx/ipfsVideoUploader#2]
It would be handy if the user would have the possibility to enter the desired steemit post. I personally tend to write both with the official uploader:
- dtube description without markdown and 
- steemit-posts with markdown and html included

Also a simple preview of the steemit-post would be good for adjusting and so on

**Comment by techcoderx** [comment]
Added [here](https://github.com/techcoderx/ipfsVideoUploader/commit/9cc2321b467c9d4e0f72eb9e622aeaa9cc5aa60e)
