### ISSUE TITLE
Users still getting "SDK" error when submitting post to the blockchain

### ISSUE THREAD

**Issue by graylan0** [techcoderx/ipfsVideoUploader#7]
After speaking to some kind people over at the steempeak discord as well as techcoderx, I believe this to be an issue with steemconnect. The user reported the error , while using Mozilla Firefox.
![image0](https://user-images.githubusercontent.com/34530588/49116197-dba0be00-f26a-11e8-867f-5bc532815d3c.jpg)

**Comment by graylan0** [comment]
The error still persists on Google Chrome, WIndows 7 64bit.

**Comment by techcoderx** [comment]
Right now posting error messages are more detailed to include details of the upload [here](https://github.com/techcoderx/ipfsVideoUploader/commit/f0f87d3c9a4d70e95721a9c9de80be62ea9f9dd7).

Could be an issue with steemconnect in windows 7

**Comment by techcoderx** [comment]
closing this since there are no recent reports of the same issue
